# Main Title

Descriptions

## Import

In [2]:
import pandas as pd

In [10]:
url = "https://raw.githubusercontent.com/deristnoor/python/refs/heads/master/project/Data%20Analytics/Manufacturing_Defect/datasets/defects_data.csv"
df = pd.read_csv(url)
df.head()

,defect_id,product_id,defect_type,defect_date,defect_location,severity,inspection_method,repair_cost
0,1,15,Structural,6/6/2024,Component,Minor,Visual Inspection,245.47
1,2,6,Functional,4/26/2024,Component,Minor,Visual Inspection,26.87
2,3,84,Structural,2/15/2024,Internal,Minor,Automated Testing,835.81
3,4,10,Functional,3/28/2024,Internal,Critical,Automated Testing,444.47
4,5,14,Cosmetic,4/26/2024,Component,Minor,Manual Testing,823.64

In [12]:
df.describe()

         defect_id   product_id  repair_cost
count  1000.000000  1000.000000  1000.000000
mean    500.500000    50.837000   507.627150
std     288.819436    29.480935   289.623615
min       1.000000     1.000000    10.220000
25%     250.750000    26.000000   270.902500
50%     500.500000    51.000000   506.430000
75%     750.250000    77.000000   759.065000
max    1000.000000   100.000000   999.640000

In [14]:
df[df.isnull() == True].count()

defect_id            0
product_id           0
defect_type          0
defect_date          0
defect_location      0
severity             0
inspection_method    0
repair_cost          0
dtype: int64

In [16]:
df.dtypes

defect_id              int64
product_id             int64
defect_type              str
defect_date              str
defect_location          str
severity                 str
inspection_method        str
repair_cost          float64
dtype: object